export enum DealStage {
    CREATIVE_AWAITING_SUBMIT = 'CREATIVE_AWAITING_SUBMIT',
    CREATIVE_AWAITING_CONFIRM = 'CREATIVE_AWAITING_CONFIRM',
    SCHEDULING_AWAITING_SUBMIT = 'SCHEDULING_AWAITING_SUBMIT',
    SCHEDULING_AWAITING_CONFIRM = 'SCHEDULING_AWAITING_CONFIRM',
    PAYMENT_AWAITING = 'PAYMENT_AWAITING',
    PAYMENT_PARTIALLY_PAID = 'PAYMENT_PARTIALLY_PAID',
    POST_SCHEDULED = 'POST_SCHEDULED',
    POST_PUBLISHING = 'POST_PUBLISHING',
    POSTED_VERIFYING = 'POSTED_VERIFYING',
    DELIVERY_CONFIRMED = 'DELIVERY_CONFIRMED',
    REFUNDING = 'REFUNDING',
    FINALIZED = 'FINALIZED',
}
