export const DEAL_TIMEOUTS = {
    PRE_DEAL_EXPIRE_MINUTES: 60,
    CREATIVE_SUBMIT_MINUTES: 30,
    ADMIN_REVIEW_HOURS: 6,
    PAYMENT_WINDOW_MINUTES: 60,
    SCHEDULE_MIN_LEAD_MINUTES: 60,
    AUTO_CANCEL_AFTER_POST_FAIL_MINUTES: 10,
} as const;
