export enum EscrowStatus {
  CREATED = 'CREATED',
  AWAITING_PAYMENT = 'AWAITING_PAYMENT',
  PAID_PARTIAL = 'PAID_PARTIAL',
  PAID_HELD = 'PAID_HELD',
  REFUND_PENDING = 'REFUND_PENDING',
  REFUNDED = 'REFUNDED',
  PAYOUT_PENDING = 'PAYOUT_PENDING',
  PAID_OUT = 'PAID_OUT',
  FAILED = 'FAILED',
}
