export enum DealStage {
    SCHEDULING_PENDING = 'SCHEDULING_PENDING',
    CREATIVE_AWAITING_SUBMIT = 'CREATIVE_AWAITING_SUBMIT',
    CREATIVE_SUBMITTED = 'CREATIVE_SUBMITTED',
    ADMIN_REVIEW_PENDING = 'ADMIN_REVIEW_PENDING',
    PAYMENT_AWAITING = 'PAYMENT_AWAITING',
    PAYMENT_PARTIALLY_PAID = 'PAYMENT_PARTIALLY_PAID',
    POST_SCHEDULED = 'POST_SCHEDULED',
    POST_PUBLISHING = 'POST_PUBLISHING',
    POSTED_VERIFYING = 'POSTED_VERIFYING',
    DELIVERY_CONFIRMED = 'DELIVERY_CONFIRMED',
    REFUNDING = 'REFUNDING',
    FINALIZED = 'FINALIZED',
}
