export enum EscrowStatus {
    CREATED = 'CREATED',
    AWAITING_PAYMENT = 'AWAITING_PAYMENT',
    PARTIALLY_PAID = 'PARTIALLY_PAID',
    PAID_CONFIRMED = 'PAID_CONFIRMED',
    RELEASED = 'RELEASED',
    REFUNDED = 'REFUNDED',
    EXPIRED = 'EXPIRED',
    FAILED = 'FAILED',
}
