export enum PinVisibilityStatus {
  NOT_REQUIRED = 'NOT_REQUIRED',
  MONITORING = 'MONITORING',
  PIN_OK = 'PIN_OK',
  PIN_MISSING_WARNED = 'PIN_MISSING_WARNED',
  PIN_MISSING_FINALIZED = 'PIN_MISSING_FINALIZED',
}
