export enum ChannelErrorCode {
    CHANNEL_NOT_FOUND = 'CHANNEL_NOT_FOUND',
    NOT_A_CHANNEL = 'NOT_A_CHANNEL',
    CHANNEL_PRIVATE_OR_NO_USERNAME = 'CHANNEL_PRIVATE_OR_NO_USERNAME',
    BOT_FORBIDDEN = 'BOT_FORBIDDEN',
    USER_NOT_ADMIN = 'USER_NOT_ADMIN',
    BOT_NOT_ADMIN = 'BOT_NOT_ADMIN',
    BOT_MISSING_RIGHTS = 'BOT_MISSING_RIGHTS',
    INVALID_USERNAME = 'INVALID_USERNAME',
}
