export const ENV = {
  NODE_ENV: 'NODE_ENV',
  BOT_TOKEN: 'BOT_TOKEN',
  TELEGRAM_ADMIN_SYNC_CRON: 'TELEGRAM_ADMIN_SYNC_CRON',
  TONCENTER_RPC: 'TONCENTER_RPC',
  TONCENTER_API_KEY: 'TONCENTER_API_KEY',
  TON_OUTGOING_MATCH_TOLERANCE_NANO: 'TON_OUTGOING_MATCH_TOLERANCE_NANO',
  TON_FINALITY_SECONDS: 'TON_FINALITY_SECONDS',
  TON_TRANSFER_TIMEOUT_SECONDS: 'TON_TRANSFER_TIMEOUT_SECONDS',
} as const;

export const NODE_ENV_VALUES = {
  LOCAL: 'local',
  STAGE: 'stage',
  PRODUCTION: 'production',
} as const;

export const ENV_LITERAL_VALUES = {
  TRUE: 'true',
} as const;
