import { User } from '../../auth/entities/user.entity';
import { ResourceOptions } from '../types/admin.types';

export function createResourceOptionsByName(
): Map<string, ResourceOptions> {
  const m = new Map<string, ResourceOptions>();

  m.set(User.name, {
    listProperties: [
      'username',
      'email',
      'lang',
      'platformType',
      'isPremium',
      'isActive',
      'credits',
      'lastLoginAt',
    ],
    showProperties: [
      'username',
      'email',
      'firstName',
      'lastName',
      'lang',
      'selectedLocation',
      'locationDefault',
      'platformType',
      'isPremium',
      'isActive',
      'onboardingPass',
      'secretOnboardingPass',
      'credits',
      'lastLoginAt',
      'authType',
      'telegramId',
      'googleId',
      'settings',
      'preferences',
      'wishesLink',
      'sendMessageAction',
    ],
    editProperties: [
      'username',
      'email',
      'firstName',
      'lastName',
      'lang',
      'platformType',
      'isPremium',
      'isActive',
      'onboardingPass',
      'secretOnboardingPass',
      'credits',
      'authType',
      'telegramId',
      'googleId',
    ],
    filterProperties: [
      'username',
      'email',
      'firstName',
      'lastName',
      'lang',
      'platformType',
      'isPremium',
      'isActive',
      'credits',
      'lastLoginAt',
      'authType',
      'onboardingPass',
      'secretOnboardingPass',
      'telegramId',
      'googleId',
      'createdAt',
    ],
    properties: {
      passwordHash: { isVisible: false },
      passwordSalt: { isVisible: false },
      emailVerificationCode: { isVisible: false },
      emailVerificationExpires: { isVisible: false },
      fbPushToken: { isVisible: false },
      iosToken: { isVisible: false },
      shareProfileId: { isVisible: false },
      surveys: { isVisible: false },
      gptQueries: { isVisible: false },
      oneTimePurchases: { isVisible: false },
      subscriptionUsers: { isVisible: false },
      bookings: { isVisible: false },
      ownedBookings: { isVisible: false },
      wishItems: { isVisible: false },
      myBookedItems: { isVisible: false },
      following: { isVisible: false },
      followers: { isVisible: false },
      createdSecretSantas: { isVisible: false },
      secretSantaParticipations: { isVisible: false },
      profileSessions: { isVisible: false },
      preferences: {
        isVisible: { list: false, filter: false, show: true, edit: false },
      },
      settings: {
        isVisible: { list: false, filter: false, show: true, edit: false },
      },
      wishesLink: {
        label: 'Wishlist',
        isVisible: { list: false, filter: false, show: true, edit: false },
        isSortable: false,
      },
    },
  });

  return m;
}
