export enum PreDealStatus {
    DRAFT = 'DRAFT',
    AWAITING_CREATIVE = 'AWAITING_CREATIVE',
    CREATIVE_SUBMITTED = 'CREATIVE_SUBMITTED',
    AWAITING_ADVERTISER_CONFIRMATION = 'AWAITING_ADVERTISER_CONFIRMATION',
    AWAITING_PUBLISHER_APPROVAL = 'AWAITING_PUBLISHER_APPROVAL',
    AWAITING_PAYMENT_WINDOW = 'AWAITING_PAYMENT_WINDOW',
    READY_FOR_PAYMENT = 'READY_FOR_PAYMENT',
    REJECTED = 'REJECTED',
    CANCELED = 'CANCELED',
    EXPIRED = 'EXPIRED',
}
