export enum DealErrorCode {
    DEAL_NOT_FOUND = 'deal.not_found',
    LISTING_NOT_FOUND = 'deal.listing_not_found',
    LISTING_DISABLED = 'deal.listing_disabled',
    UNAUTHORIZED = 'deal.unauthorized',
    UNAUTHORIZED_DEAL_ACCESS = 'deal.unauthorized_deal_access',
    INVALID_SCHEDULE_TIME = 'deal.invalid_schedule_time',
    INVALID_STATUS = 'deal.invalid_status',
    SELF_DEAL_NOT_ALLOWED = 'deal.self_deal_not_allowed',
    ACTIVE_PENDING_LIMIT_REACHED = 'deal.active_pending_limit_reached',
    DEADLINE_PASSED = 'deal.deadline_passed',
    CREATIVE_NOT_SUBMITTED = 'deal.creative_not_submitted',
    PAYMENT_TIMEOUT = 'deal.payment_timeout',
    CREATIVE_TIMEOUT = 'deal.creative_timeout',
}
