export const TON_DEFAULTS = {
  OUTGOING_MATCH_TOLERANCE_NANO: 200000n,
  FINALITY_SECONDS: 120,
  TRANSFER_TIMEOUT_SECONDS: 1800,
  OUTGOING_MATCH_WINDOW_MS: 2 * 60 * 60 * 1000,
  OUTGOING_TX_LIMIT_MIN: 20,
  OUTGOING_TX_LIMIT_MAX: 100,
  OUTGOING_TX_LIMIT_MULTIPLIER: 5,
  INCOMING_TX_LIMIT: 50,
} as const;
