export enum TransactionStatus {
    PENDING = 'PENDING',
    PARTIAL = 'PARTIAL',
    AWAITING_CONFIRMATION = 'AWAITING_CONFIRMATION',
    CONFIRMED = 'CONFIRMED',
    COMPLETED = 'COMPLETED',
    REFUNDED = 'REFUNDED',
    BLOCKED_LIQUIDITY = 'BLOCKED_LIQUIDITY',
    FAILED = 'FAILED',
    CANCELED = 'CANCELED',
}
