export enum TransactionStatus {
  PENDING = 'PENDING',
  PARTIAL = 'PARTIAL',
  AWAITING_CONFIRMATION = 'AWAITING_CONFIRMATION',
  CONFIRMED = 'CONFIRMED',
  COMPLETED = 'COMPLETED',
  BLOCKED_LIQUIDITY = 'BLOCKED_LIQUIDITY',
  REFUNDED = 'REFUNDED',
  FAILED = 'FAILED',
  CANCELED = 'CANCELED',
}
